---
services:
  web:
    container_name: btwebAPP
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}

  db:
    container_name: btwebDB
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydatabase

volumes:
  postgres_data:
